import { ReactNode } from 'react'
import localFont from 'next/font/local'
import HeaderAndSidebar from '@/components/templates/header-and-sidebar'

import type { Metadata } from 'next'
import '../globals.css'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Beauty Scandal Pro',
  description: 'Generated by create next app',
}

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeaderAndSidebar>{children}</HeaderAndSidebar>
      </body>
    </html>
  )
}
